name = "Trabalho"
version = "0.1.0"
license = "license"
author = "Kaio Alvear"
maintainer = "kaio.chagas@ufv.br"
copyright = "Copyright 2025, Jane Doe"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

